### ISSUE TITLE
Server requires open (pseudo-)tty

### ISSUE THREAD

**Issue by StiviiK** [altmp/altv#450]
**Expected behavior**
The server should be running in a container without an open tty like a charm.

**Current behavior**
The server gets stuck when no tty is attached.

**Steps to reproduce**
Docker Image used: https://github.com/StiviiK/altv

Without tty gets stuck:
```docker run --rm --name altv stivik/altv:rc```

With tty works normaly:
```docker run -t --rm --name altv_tty stivik/altv:rc```

Docker-compose examples:
Without tty gets stuck:
```
version: '3.7'
services:
  develop:
    image: stivik/altv:rc
    container_name: game_develop
    restart: always
    ports:
      - 7788:7788/tcp
      - 7788:7788/udp
```

With tty works normaly:
```
version: '3.7'
services:
  develop:
    image: stivik/altv:rc
    container_name: game_develop
    restart: always
    tty: true
    ports:
      - 7788:7788/tcp
      - 7788:7788/udp
```
